version: '3'

networks:
  simdiklat:
  # besimdocker_app-shared: 
  #   external: true
services:
  nginx: 
    image: nginx:stable-alpine
    container_name: nginx
    ports: 
      - "8087:80"
    volumes:
      - ./src:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - mysql
    networks:
      - simdiklat
      # - besimdocker_app-shared

  mysql:
    image: mysql:latest
    container_name: mysql
    restart: unless-stopped
    tty: true
    ports: 
    - "63306:3306"
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      MYSQL_DATABASE: simdiklat
      MYSQL_USER: rahmat
      MYSQL_PASSWORD: efotoadmin
      MYSQL_ROOT_PASSWORD: efotoadmin
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    networks:
     - simdiklat

  php:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: php
    volumes:
        - ./src:/var/www/html
        - ./php/custom.ini:/usr/local/etc/php/conf.d/custom.ini
    ports:
        - "9000:9000"
    networks:
      - simdiklat
      # - besimdocker_app-shared

  redis:
    image: redis:6.2-alpine
    restart: unless-stopped
    ports:
      - '7379:6379'
    command: redis-server --save 20 1 --loglevel warning --requirepass efotoadmin
    volumes: 
      - ./redis:/data
    networks:
      - simdiklat
  
  npm:
    image: node:lts-alpine3.15
    container_name: npm
    volumes:
      - ./src:/var/www/html
    working_dir: /var/www/html
    entrypoint: ['npm']
    networks:
      - simdiklat
  
  artisan:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: artisan
    volumes:
      - ./src:/var/www/html
    depends_on:
      - mysql
    working_dir: /var/www/html
    entrypoint: ['/var/www/html/artisan']
    networks:
      - simdiklat
    
